from Data_base_tool import DatabaseIteraction
def additems():
    ne_list = ['Sticker | Web Stuck (Holo)',
    'Sticker | G2 (Holo) | 2020 RMR',
    'Sticker | Eternal Fire (Glitter) | Antwerp 2022',
    'Sticker | Natus Vincere (Glitter) | Antwerp 2022',
    'Sticker | Copenhagen Flames (Glitter) | Antwerp 2022',
    'Sticker | Team Liquid (Glitter) | Antwerp 2022',
    'Sticker | Liquid (Holo) | 2020 RMR',
    'Sticker | FURIA (Holo) | 2020 RMR',
    'Sticker | Virtus.pro (Holo) | 2020 RMR',
    'Sticker | Ninjas in Pyjamas (Glitter) | Antwerp 2022',
    'CS20 Case',
    'Dreams & Nightmares Case',
    'Sticker | FaZe (Holo) | 2020 RMR',
    'Stockholm 2021 Champions Autograph Capsule',
    'Sticker | Fnatic (Holo) | 2020 RMR',
    'Sticker | s1mple (Holo) | Stockholm 2021',
    'Sticker | PGL (Glitter) | Antwerp 2022',
    'Clutch Case',
    'Antwerp 2022 Challengers Sticker Capsule',
    'Sticker | TYLOO (Holo) | 2020 RMR',
    'Sticker | Tyloo | Stockholm 2021',
    'Sticker | Virtus.Pro | Stockholm 2021',
    '2020 RMR Contenders',
    'Antwerp 2022 Legends Sticker Capsule',
    'Rio 2022 Contenders Sticker Capsule',
    'Sticker | kennyS | Berlin 2019',
    'Sticker | Eternal Fire | Antwerp 2022',
    'Glock-18 | Off World (Factory New)',
    'Spectrum 2 Case',
    'Antwerp 2022 Contenders Sticker Capsule',
    'Recoil Case',
    'Fracture Case',
    'Danger Zone Case',
    'Rio 2022 Challengers Sticker Capsule',
    'Prisma 2 Case',
    'Horizon Case',
    'Shadow Case',
    'Falchion Case',
    'Antwerp 2022 Contenders Autograph Capsule',
    'Sticker | Natus Vincere (Foil) | 2020 RMR',
    'Name Tag',
    'Sticker | electroNic (Holo) | Stockholm 2021',
    'Sticker | Natus Vincere (Holo) | 2020 RMR',
    'Sticker | b1t (Holo) | Stockholm 2021',
    'Sticker | Astralis (Holo) | 2020 RMR',
    'Sticker | BIG (Glitter) | Antwerp 2022',
    'Sticker | North (Holo) | 2020 RMR',
    'Sticker | Cloud9 | Antwerp 2022',
    'Sticker | Natus Vincere | Antwerp 2022',
    'Stockholm 2021 Contenders Sticker Capsule',
    'Operation Phoenix Weapon Case',
    'Stockholm 2021 Challengers Sticker Capsule',
    'Operation Broken Fang Case',
    'Rezan The Ready | Sabre',
    "'The Doctor' Romanov | Sabre",
    'Sticker | Cloud9 (Glitter) | Antwerp 2022',
    'Sticker | Gold Web (Foil)',
    'Music Kit | Denzel Curry, ULTIMATE',
    'Music Kit | The Verkkars, EZ4ENCE',
    'Michael Syfers | FBI Sniper',
    'Blackwolf | Sabre',
    'Revolution Case',
    'Operation Wildfire Case',
    'Stockholm 2021 Legends Sticker Capsule',
    'Shattered Web Case',
    'Anubis Collection Package',
    'Sticker | Gambit Gaming (Holo) | Stockholm 2021',
    'Sticker | Team Liquid (Holo) | Stockholm 2021',
    'Sticker | FaZe Clan (Holo) | Antwerp 2022',
    'Sticker | Vitality (Holo) | Stockholm 2021',
    'Sticker | G2 Esports (Glitter) | Antwerp 2022',
    'Sticker | Drug War Veteran',
    'Sticker | Salty (Holo)',
    'Sticker | Battle Scarred',
    'Sticker | Blue Gem (Glitter)',
    'Music Kit | bbno$, u mad!',
    'Sticker | Baby Howl',
    'Sticker | Conspiracy Club (Holo)',
    'Sticker | Boombl4 (Holo) | Stockholm 2021',
    'StatTrak™ Desert Eagle | Trigger Discipline (Field-Tested)',
    'StatTrak™ Desert Eagle | Light Rail (Field-Tested)',
    'Sticker Capsule',
    'M4A1-S | Nitro (Field-Tested)',
    'Sticker | m0NESY (Glitter) | Antwerp 2022']

    connection = DatabaseIteraction()
    n = 0
    for i in ne_list:
        n+= 1 
        connection.AddItemsInOperation(str(n), i)